#!/usr/bin/env bash
# Pushes the sibling .env file into the VM's /etc/profile.d/tart-provision.sh.
# All TCTL_ variables are injected by tart-ctl.sh before this script runs.
# TCTL_CONFIG_DIR points to the directory containing .tart-ctl-env and .env.
set -euo pipefail

# The .env file lives alongside .tart-ctl-env (not inside the provision dir)
ENV_FILE="${TCTL_CONFIG_DIR}/.env"
PROFILE_DEST="/etc/profile.d/tart-provision.sh"

echo "  Source .env: ${ENV_FILE}"
echo "  Target     : ${TCTL_SSH_USER}@${TCTL_VM_NAME}:${PROFILE_DEST}"
echo "  SSH config : ${TCTL_SSH_CONFIG}"
echo "  Identity   : ${TCTL_IDENTITY_FILE}"
echo

# Base64-encode .env to safely transfer special characters to the VM.
if [[ -f "${ENV_FILE}" ]]; then
  local_line_count=$(grep -c '.' "${ENV_FILE}" || true)
  echo "  Reading ${ENV_FILE} (${local_line_count} line(s)) …"
  ENV_B64=$(base64 < "${ENV_FILE}")
else
  echo "  [warn] No .env file found at ${ENV_FILE} — pushing empty environment."
  ENV_B64=$(base64 < /dev/null)
fi

echo "  Transferring environment to VM …"
ssh -T \
  -F "${TCTL_SSH_CONFIG}" \
  -i "${TCTL_IDENTITY_FILE}" \
  "${TCTL_SSH_USER}@${TCTL_VM_NAME}" bash << ENDSSH
set -euo pipefail
PROFILE_FILE='${PROFILE_DEST}'
TMPFILE=\$(mktemp)

echo "  [vm] Writing profile script to \$PROFILE_FILE …"

# Write the shell script header
{
  echo '#!/usr/bin/env bash'
  echo '# Generated by tart-ctl provision — do not edit manually'
  echo
} > "\$TMPFILE"

export_count=0
skip_count=0

# Decode .env content and convert each key=value line to an export statement
while IFS= read -r line || [[ -n "\$line" ]]; do
  # Trim leading/trailing whitespace
  line="\${line#"\${line%%[![:space:]]*}"}"
  line="\${line%"\${line##*[![:space:]]}"}"

  # Skip empty lines and comments
  [[ -z "\$line" || "\$line" == \#* ]] && continue

  # Split on first '='
  key="\${line%%=*}"
  value="\${line#*=}"

  # Trim whitespace around key
  key="\${key%"\${key##*[![:space:]]}"}"

  # Remove optional surrounding quotes from value
  if [[ "\$value" =~ ^\".*\"\$ ]]; then
    value="\${value:1:-1}"
  elif [[ "\$value" =~ ^\'.*\'\$ ]]; then
    value="\${value:1:-1}"
  fi

  # Validate key (POSIX-like variable name)
  if [[ ! "\$key" =~ ^[A-Za-z_][A-Za-z0-9_]*\$ ]]; then
    echo "  [vm] Skipping invalid key: \$key" >&2
    (( skip_count++ )) || true
    continue
  fi

  # Escape value safely and write export statement
  escaped_value=\$(printf '%q' "\$value")
  echo "export \$key=\$escaped_value"
  echo "  [vm] Exporting: \$key" >&2
  (( export_count++ )) || true
done < <(echo '${ENV_B64}' | base64 -d) >> "\$TMPFILE"

sudo cp "\$TMPFILE" "\$PROFILE_FILE"
sudo chmod 644 "\$PROFILE_FILE"
rm -f "\$TMPFILE"

echo "  [vm] Done — \$export_count variable(s) exported, \$skip_count skipped."
echo "  [vm] Profile written to \$PROFILE_FILE"
ENDSSH

echo "  Environment initialised successfully."
