#!/usr/bin/env bash
# Pushes a local env file into the VM's /etc/profile.d/tart-provision.sh.
# Resolution order: .env.local → .env → empty fallback.
# All TCTL_ variables are injected by tart-ctl.sh before this script runs.
# TCTL_CONFIG_DIR points to the directory containing .tart-ctl-env, .env, and .env.local.
set -euo pipefail

# The .env file lives alongside .tart-ctl-env (not inside the provision dir)
ENV_FILE="${TCTL_CONFIG_DIR}/.env"
PROFILE_DEST="/etc/profile.d/tart-provision.sh"

echo "  Target     : ${TCTL_SSH_USER}@${TCTL_VM_NAME}:${PROFILE_DEST}"
echo "  SSH config : ${TCTL_SSH_CONFIG}"
echo "  Identity   : ${TCTL_IDENTITY_FILE}"
echo

# Base64-encode env file to safely transfer special characters to the VM.
# Resolution order: .env.local → .env → empty fallback
ENV_FILE_LOCAL="${TCTL_CONFIG_DIR}/.env.local"

echo "  Resolving env file (config dir: ${TCTL_CONFIG_DIR}) …"
if [[ -f "${ENV_FILE_LOCAL}" || -p "${ENV_FILE_LOCAL}" ]]; then
  RESOLVED_ENV_FILE="${ENV_FILE_LOCAL}"
  echo "  [✓] Found .env.local — using ${RESOLVED_ENV_FILE}"
elif [[ -f "${ENV_FILE}" || -p "${ENV_FILE}" ]]; then
  RESOLVED_ENV_FILE="${ENV_FILE}"
  echo "  [✓] Found .env — using ${RESOLVED_ENV_FILE}"
  echo "  [i] Tip: create .env.local to override without modifying .env"
else
  RESOLVED_ENV_FILE=""
  echo "  [warn] Neither .env.local nor .env found in ${TCTL_CONFIG_DIR} — pushing empty environment."
fi

if [[ -n "${RESOLVED_ENV_FILE}" ]]; then
  local_line_count=$(grep -c '.' "${RESOLVED_ENV_FILE}" || true)
  echo "  Reading ${RESOLVED_ENV_FILE} (${local_line_count} non-empty line(s)) …"
  ENV_B64=$(base64 < "${RESOLVED_ENV_FILE}")
else
  ENV_B64=$(base64 < /dev/null)
fi

echo
echo "  Transferring environment to VM …"
ssh -T \
  -F "${TCTL_SSH_CONFIG}" \
  -i "${TCTL_IDENTITY_FILE}" \
  "${TCTL_SSH_USER}@${TCTL_VM_NAME}" bash << ENDSSH
set -euo pipefail
PROFILE_FILE='${PROFILE_DEST}'
TMPFILE=\$(mktemp)

echo "  [vm] Writing profile script to \$PROFILE_FILE …"

# Write the shell script header
{
  echo '#!/usr/bin/env bash'
  echo '# Generated by tart-ctl provision — do not edit manually'
  echo
} > "\$TMPFILE"

export_count=0
skip_count=0

# Decode .env content and convert each key=value line to an export statement
while IFS= read -r line || [[ -n "\$line" ]]; do
  # Trim leading/trailing whitespace
  line="\${line#"\${line%%[![:space:]]*}"}"
  line="\${line%"\${line##*[![:space:]]}"}"

  # Skip empty lines and comments
  [[ -z "\$line" || "\$line" == \#* ]] && continue

  # Split on first '='
  key="\${line%%=*}"
  value="\${line#*=}"

  # Trim whitespace around key
  key="\${key%"\${key##*[![:space:]]}"}"

  # Remove optional surrounding quotes from value
  if [[ "\$value" =~ ^\".*\"\$ ]]; then
    value="\${value:1:-1}"
  elif [[ "\$value" =~ ^\'.*\'\$ ]]; then
    value="\${value:1:-1}"
  fi

  # Validate key (POSIX-like variable name)
  if [[ ! "\$key" =~ ^[A-Za-z_][A-Za-z0-9_]*\$ ]]; then
    echo "  [vm] Skipping invalid key: \$key" >&2
    (( skip_count++ )) || true
    continue
  fi

  # Escape value safely and write export statement
  escaped_value=\$(printf '%q' "\$value")
  echo "export \$key=\$escaped_value"
  echo "  [vm] Exporting: \$key" >&2
  (( export_count++ )) || true
done < <(echo '${ENV_B64}' | base64 -d) >> "\$TMPFILE"

sudo cp "\$TMPFILE" "\$PROFILE_FILE"
sudo chmod 644 "\$PROFILE_FILE"
rm -f "\$TMPFILE"

echo "  [vm] Done — \$export_count variable(s) exported, \$skip_count skipped."
echo "  [vm] Profile written to \$PROFILE_FILE"
ENDSSH

echo
echo "  Environment initialised successfully."
echo "  Source file : ${RESOLVED_ENV_FILE:-"(none — empty environment pushed)"}"
echo "  Target      : ${TCTL_SSH_USER}@${TCTL_VM_NAME}:${PROFILE_DEST}"
